name: Ubuntu Desktop Development Series Feedback
description: Provide feedback for Ubuntu Desktop Development Series
title: "A short summary of your feedback"
labels: [Feedback]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Briefly describe your overall impression.
    validations:
      required: false
  - type: textarea
    id: positives
    attributes:
      label: Positives
      description: Please list or describe what you liked.
    validations:
      required: false
  - type: textarea
    id: negatives
    attributes:
      label: Negatives
      description: Please list or describe any problems or issues you encountered.
    validations:
      required: false
  - type: textarea
    id: suggestions
    attributes:
      label: Suggestions for Improvement
      description: If applicable, provide any suggestions or ideas for improving the Ubuntu Desktop development release.
    validations:
      required: false
  - type: textarea
    id: hardware
    attributes:
      label: Hardware Specifications
      description: Describe the hardware you are using (cpu, gpu, monitors, etc).
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Include any additional information or context that might be helpful.
    validations:
      required: false
